/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kt_iot_mobile_ui_activity_OpencvActivity */

#ifndef _Included_com_kt_iot_mobile_ui_activity_OpencvActivity
#define _Included_com_kt_iot_mobile_ui_activity_OpencvActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_kt_iot_mobile_ui_activity_OpencvActivity_PERMISSION_REQUEST_CODE
#define com_kt_iot_mobile_ui_activity_OpencvActivity_PERMISSION_REQUEST_CODE 1L
/*
 * Class:     com_kt_iot_mobile_ui_activity_OpencvActivity
 * Method:    loadImage
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_kt_iot_mobile_ui_activity_OpencvActivity_loadImage
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_kt_iot_mobile_ui_activity_OpencvActivity
 * Method:    imageprocessing
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_kt_iot_mobile_ui_activity_OpencvActivity_imageprocessing
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
